### ISSUE TITLE
Emotes don't work after the latest Discord update

### ISSUE THREAD

**Issue by ToonLucas22** [Jiiks/BetterDiscordApp#314]
Today (May 19th, 2016), a new Discord update was released with server sorting and whatnot. The problem is that emotes don't work when using BetterDiscord with that update. The menu still works, though.

**Comment by barlowjp** [comment]
I'm finding this to be an issue as well. Sub emotes attached to twitch seem to be working, but other emotes associated with bttv and twitch do not appear for myself and many others in our server.

**Comment by ToonLucas22** [comment]
Seems like the problem is solved (hotfixes everywhere), but there is a slight delay before the thing turns into an emote.

**Comment by GoaLitiuM** [comment]
I just updated both Discord and BetterDiscord and BTTV/FFZ emotes are still not displaying properly.

**Comment by Jiiks** [comment]
Fixed a while back
